version: '3'
services:
# core
  node:
    image: mysteriumnetwork/myst:latest
    command:
      - '--udp.ports=59850:60000'
      - 'service --agreed-terms-and-conditions'
    networks:
      - myst
      - proxy_n
    expose:
      - 4449
    ports:
#      - '192.168.44.1:4449:4449' # change this to your VPN IP
      - '59850-60000:59850-60000/udp'
    container_name: it2-myst # change this as you wish
    cap_add:
      - NET_ADMIN
    volumes:
      - '/var/lib/mysterium-node:/var/lib/mysterium-node'
      - '/etc/mysterium-node:/etc/mysterium-node'
    restart: unless-stopped

  dashboard:
    image: lscr.io/linuxserver/heimdall
    container_name: dashboard
    env_file: ./envs/.env_dashboard
    networks:
      - proxy_d
    volumes:
      - /etc/heimdall:/config
    restart: unless-stopped

  proxy:
    image: ghcr.io/linuxserver/swag:latest
    container_name: proxy
    cap_add:
      - NET_ADMIN
    env_file: ./envs/.env_proxy
    networks:
      - proxy_n
      - proxy_m
      - proxy_d
      - proxy_wg
    volumes:
      - /etc/swag:/config
    ports:
      - 443:443/tcp
      - 80:80/tcp
    depends_on:
      - dashboard
      - node
    restart: unless-stopped

# monitoring
  uptime-mon:
    container_name: uptime
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    networks: # port 3001
      - proxy_m
    volumes:
      - /etc/uptime-kuma:/app/data
    depends_on:
      - node

# wireguard services
  wg-gen-web:
    image: vx3r/wg-gen-web:latest
    container_name: vpn
    restart: unless-stopped
    networks: # port 8080
      - proxy_wg
    env_file: ./envs/.env_wg_gen_web
    volumes:
      - /etc/wireguard:/data
    depends_on:
      - wg-json-api

  wg-json-api:
    image: james/wg-api:latest
    #build:
    #  context: ./wg-api
    container_name: vpn-api
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: wg-api --device wg0 --listen 172.17.0.1:8182

# Watchtower
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# DNS

# Security

    
networks:
  myst:
    name: myst
    driver: bridge
  proxy_n:
    name: proxy_n
    driver: bridge
  proxy_m:
    name: proxy_m
    driver: bridge
  proxy_d:
    name: proxy_d
    driver: bridge 
  proxy_wg:
    name: proxy_wg
    driver: bridge 